name: Node.js CI

on:
  push:
    branches: [ master, chag/usecase ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Run script
        run: node index.js

      - name: Run test
        run: node test.js
